#!/bin/bash
# gen_icons.sh
# 从 assets/logo.png 自动生成 Android 和 iOS 应用图标
#
# 使用方式: bash scripts/gen_icons.sh
#
# 依赖: flutter_launcher_icons (已在 pubspec.yaml dev_dependencies 中配置)
# 配置: flutter_launcher_icons.yaml

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "==> 生成应用图标..."
echo "    源文件: assets/logo.png"
echo "    配置:   flutter_launcher_icons.yaml"
echo ""

cd "$PROJECT_DIR"

# flutter_launcher_icons 0.9.3 硬编码读取 build.gradle，不支持 .kts
# 创建临时的 build.gradle 供脚本读取
TEMP_GRADLE="android/app/build.gradle"
NEED_CLEANUP=false

if [ ! -f "$TEMP_GRADLE" ]; then
  NEED_CLEANUP=true
  cat > "$TEMP_GRADLE" << 'GRADLE'
// TEMPORARY — workaround for flutter_launcher_icons 0.9.3 (cannot parse build.gradle.kts)
// Auto-generated by scripts/gen_icons.sh — do not edit manually
android {
    defaultConfig {
        minSdkVersion 21
    }
}
GRADLE
  echo "    创建临时 build.gradle (flutter_launcher_icons 兼容)"
fi

# 运行图标生成
flutter pub run flutter_launcher_icons:main

# 清理临时文件
if [ "$NEED_CLEANUP" = true ]; then
  rm -f "$TEMP_GRADLE"
  echo "    已清理临时 build.gradle"
fi

echo ""
echo "==> 图标生成完成"
echo ""
echo "    Android: android/app/src/main/res/mipmap-*/ic_launcher.png"
echo "    Android 自适应: android/app/src/main/res/drawable-*/ic_launcher_foreground.png"
echo "    iOS: ios/Runner/Assets.xcassets/AppIcon.appiconset/"
